/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DraftDraftsInnerRoundsInner {
    #[serde(rename = "roundNumber", skip_serializing_if = "Option::is_none")]
    pub round_number: Option<f32>,
    #[serde(rename = "round", skip_serializing_if = "Option::is_none")]
    pub round: Option<f32>,
    #[serde(rename = "picks", skip_serializing_if = "Option::is_none")]
    pub picks: Option<Vec<crate::models::DraftDraftsInnerRoundsInnerPicksInner>>,
}

impl DraftDraftsInnerRoundsInner {
    pub fn new() -> DraftDraftsInnerRoundsInner {
        DraftDraftsInnerRoundsInner {
            round_number: None,
            round: None,
            picks: None,
        }
    }
}


