/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DraftDraftsInnerRoundsInnerPicksInner {
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<f32>,
    #[serde(rename = "round", skip_serializing_if = "Option::is_none")]
    pub round: Option<String>,
    #[serde(rename = "pickOverall", skip_serializing_if = "Option::is_none")]
    pub pick_overall: Option<f32>,
    #[serde(rename = "pickInRound", skip_serializing_if = "Option::is_none")]
    pub pick_in_round: Option<f32>,
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<Box<crate::models::DraftDraftsInnerRoundsInnerPicksInnerTeam>>,
    #[serde(rename = "prospect", skip_serializing_if = "Option::is_none")]
    pub prospect: Option<Box<crate::models::DraftDraftsInnerRoundsInnerPicksInnerProspect>>,
}

impl DraftDraftsInnerRoundsInnerPicksInner {
    pub fn new() -> DraftDraftsInnerRoundsInnerPicksInner {
        DraftDraftsInnerRoundsInnerPicksInner {
            year: None,
            round: None,
            pick_overall: None,
            pick_in_round: None,
            team: None,
            prospect: None,
        }
    }
}


