/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameBoxscoreTeamCoachesInner {
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<Box<crate::models::GameBoxscoreTeamCoachesInnerPerson>>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<Box<crate::models::GameBoxscoreTeamCoachesInnerPosition>>,
}

impl GameBoxscoreTeamCoachesInner {
    pub fn new() -> GameBoxscoreTeamCoachesInner {
        GameBoxscoreTeamCoachesInner {
            person: None,
            position: None,
        }
    }
}


