/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameContentHighlights {
    #[serde(rename = "scoreboard", skip_serializing_if = "Option::is_none")]
    pub scoreboard: Option<Box<crate::models::GameHighlights>>,
    #[serde(rename = "gameCenter", skip_serializing_if = "Option::is_none")]
    pub game_center: Option<Box<crate::models::GameHighlights>>,
}

impl GameContentHighlights {
    pub fn new() -> GameContentHighlights {
        GameContentHighlights {
            scoreboard: None,
            game_center: None,
        }
    }
}


