/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameHighlightPlaybacksInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Name>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<String>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl GameHighlightPlaybacksInner {
    pub fn new() -> GameHighlightPlaybacksInner {
        GameHighlightPlaybacksInner {
            name: None,
            width: None,
            height: None,
            url: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "FLASH_192K_320X180")]
    Flash192K320X180,
    #[serde(rename = "FLASH_450K_400X224")]
    Flash450K400X224,
    #[serde(rename = "FLASH_1200K_640X360")]
    Flash1200K640X360,
    #[serde(rename = "FLASH_1800K_960X540")]
    Flash1800K960X540,
    #[serde(rename = "HTTP_CLOUD_MOBILE")]
    HttpCloudMobile,
    #[serde(rename = "HTTP_CLOUD_TABLET")]
    HttpCloudTablet,
    #[serde(rename = "HTTP_CLOUD_TABLET_60")]
    HttpCloudTablet60,
    #[serde(rename = "HTTP_CLOUD_WIRED")]
    HttpCloudWired,
    #[serde(rename = "HTTP_CLOUD_WIRED_60")]
    HttpCloudWired60,
    #[serde(rename = "HTTP_CLOUD_WIRED_WEB")]
    HttpCloudWiredWeb,
}

impl Default for Name {
    fn default() -> Name {
        Self::Flash192K320X180
    }
}

