/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameGameData {
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<Box<crate::models::GameGameDataGame>>,
    #[serde(rename = "datetime", skip_serializing_if = "Option::is_none")]
    pub datetime: Option<Box<crate::models::GameGameDataDatetime>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::GameGameDataStatus>>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Box<crate::models::GameGameDataTeams>>,
    #[serde(rename = "players", skip_serializing_if = "Option::is_none")]
    pub players: Option<Box<crate::models::Player>>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<Box<crate::models::GameGameDataVenue>>,
}

impl GameGameData {
    pub fn new() -> GameGameData {
        GameGameData {
            game: None,
            datetime: None,
            status: None,
            teams: None,
            players: None,
            venue: None,
        }
    }
}


