/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameBoxscoreTeamCoachesInnerPosition {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "abbreviation", skip_serializing_if = "Option::is_none")]
    pub abbreviation: Option<String>,
}

impl GameBoxscoreTeamCoachesInnerPosition {
    pub fn new() -> GameBoxscoreTeamCoachesInnerPosition {
        GameBoxscoreTeamCoachesInnerPosition {
            code: None,
            name: None,
            r#type: None,
            abbreviation: None,
        }
    }
}


