/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameEditorialContributorContributorsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "twitter", skip_serializing_if = "Option::is_none")]
    pub twitter: Option<String>,
}

impl GameEditorialContributorContributorsInner {
    pub fn new() -> GameEditorialContributorContributorsInner {
        GameEditorialContributorContributorsInner {
            name: None,
            twitter: None,
        }
    }
}


