/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameContentEditorial {
    #[serde(rename = "preview", skip_serializing_if = "Option::is_none")]
    pub preview: Option<Box<crate::models::GameEditorials>>,
    #[serde(rename = "articles", skip_serializing_if = "Option::is_none")]
    pub articles: Option<Box<crate::models::GameEditorials>>,
    #[serde(rename = "recap", skip_serializing_if = "Option::is_none")]
    pub recap: Option<Box<crate::models::GameEditorials>>,
}

impl GameContentEditorial {
    pub fn new() -> GameContentEditorial {
        GameContentEditorial {
            preview: None,
            articles: None,
            recap: None,
        }
    }
}


