/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameBoxscoreTeamOnIcePlusInner {
    #[serde(rename = "playerId", skip_serializing_if = "Option::is_none")]
    pub player_id: Option<f32>,
    #[serde(rename = "shiftDuration", skip_serializing_if = "Option::is_none")]
    pub shift_duration: Option<f32>,
    #[serde(rename = "stamina", skip_serializing_if = "Option::is_none")]
    pub stamina: Option<f32>,
}

impl GameBoxscoreTeamOnIcePlusInner {
    pub fn new() -> GameBoxscoreTeamOnIcePlusInner {
        GameBoxscoreTeamOnIcePlusInner {
            player_id: None,
            shift_duration: None,
            stamina: None,
        }
    }
}


