/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Photo {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "altText", skip_serializing_if = "Option::is_none")]
    pub alt_text: Option<String>,
    #[serde(rename = "cuts", skip_serializing_if = "Option::is_none")]
    pub cuts: Option<Box<crate::models::PhotoCuts>>,
}

impl Photo {
    pub fn new() -> Photo {
        Photo {
            title: None,
            alt_text: None,
            cuts: None,
        }
    }
}


