/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlayerStatsStatsInnerType {
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<DisplayName>,
}

impl PlayerStatsStatsInnerType {
    pub fn new() -> PlayerStatsStatsInnerType {
        PlayerStatsStatsInnerType {
            display_name: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DisplayName {
    #[serde(rename = "byDayOfWeek")]
    ByDayOfWeek,
    #[serde(rename = "byMonth")]
    ByMonth,
    #[serde(rename = "goalsByGameSituation")]
    GoalsByGameSituation,
    #[serde(rename = "homeAndAway")]
    HomeAndAway,
    #[serde(rename = "onPaceRegularSeason")]
    OnPaceRegularSeason,
    #[serde(rename = "regularSeasonStatRankings")]
    RegularSeasonStatRankings,
    #[serde(rename = "statsSingleSeason")]
    StatsSingleSeason,
    #[serde(rename = "vsConference")]
    VsConference,
    #[serde(rename = "vsDivision")]
    VsDivision,
    #[serde(rename = "vsTeam")]
    VsTeam,
    #[serde(rename = "winLoss")]
    WinLoss,
}

impl Default for DisplayName {
    fn default() -> DisplayName {
        Self::ByDayOfWeek
    }
}

