/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamStatsStatsInner {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<crate::models::TeamStatsStatsInnerType>>,
    #[serde(rename = "splits", skip_serializing_if = "Option::is_none")]
    pub splits: Option<Vec<crate::models::TeamStatsStatsInnerSplitsInner>>,
}

impl TeamStatsStatsInner {
    pub fn new() -> TeamStatsStatsInner {
        TeamStatsStatsInner {
            r#type: None,
            splits: None,
        }
    }
}


