/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamNextGameScheduleDatesInnerGamesInnerTeamsAway {
    #[serde(rename = "leagueRecord", skip_serializing_if = "Option::is_none")]
    pub league_record: Option<Box<crate::models::TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayLeagueRecord>>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<Box<crate::models::TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam>>,
}

impl TeamNextGameScheduleDatesInnerGamesInnerTeamsAway {
    pub fn new() -> TeamNextGameScheduleDatesInnerGamesInnerTeamsAway {
        TeamNextGameScheduleDatesInnerGamesInnerTeamsAway {
            league_record: None,
            score: None,
            team: None,
        }
    }
}


