/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamStatsStatsInnerType {
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl TeamStatsStatsInnerType {
    pub fn new() -> TeamStatsStatsInnerType {
        TeamStatsStatsInnerType {
            display_name: None,
        }
    }
}


