/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamStatsStatsInnerSplitsInner {
    #[serde(rename = "stat", skip_serializing_if = "Option::is_none")]
    pub stat: Option<Box<crate::models::TeamStatsStatsInnerSplitsInnerStat>>,
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<Box<crate::models::PlayerCurrentTeam>>,
}

impl TeamStatsStatsInnerSplitsInner {
    pub fn new() -> TeamStatsStatsInnerSplitsInner {
        TeamStatsStatsInnerSplitsInner {
            stat: None,
            team: None,
        }
    }
}


